name: visitbogor
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  animated_text_kit: ^4.2.1
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  flutter_staggered_grid_view: ^0.4.1
  get: 4.6.1
  http: ^0.13.4
  jiffy: ^4.1.0
  lottie: ^1.2.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  lints: 1.0.1

flutter:
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  # lokasi image lokal
  assets:
    - assets/images/logo.png
